import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import {
  automatorStatusEnum,
  campaignPostStatusEnum,
  socialCampaignStatusEnum,
  socialPostStatusEnum,
} from "./_enums.js";
import { fk, pk, timestamps } from "./_helpers.js";
import { reviews } from "./reviews.js";
import { profiles } from "./tenancy.js";

/** v1 `social_stream` → `social_accounts` — a connected social account. OAuth tokens encrypted at rest. */
export const socialAccounts = pgTable(
  "social_accounts",
  {
    id: pk(),
    profileId: fk("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    name: varchar("name", { length: 255 }),
    page: varchar("page", { length: 255 }),
    pageId: varchar("page_id", { length: 255 }).notNull().default(""),
    authorizationId: varchar("authorization_id", { length: 255 }).notNull().default(""),
    authorizationToken: text("authorization_token"),
    authorizationSecret: varchar("authorization_secret", { length: 255 }),
    authorizationExpiry: timestamp("authorization_expiry", { withTimezone: true }),
    signatureKey: varchar("signature_key", { length: 255 }),
    active: boolean("active").notNull().default(true),
    lastScrapedAt: timestamp("last_scraped_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    attempts: integer("attempts").notNull().default(0),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }),
    ...timestamps,
  },
  (t) => [index("social_accounts_profile_idx").on(t.profileId)],
);

/** v1 `social_post` — an individual social post (often sharing a review). */
export const socialPosts = pgTable(
  "social_posts",
  {
    id: pk(),
    profileId: fk("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    socialAccountId: fk("social_account_id").references(() => socialAccounts.id, {
      onDelete: "set null",
    }),
    reviewId: fk("review_id").references(() => reviews.id, { onDelete: "set null" }),
    socialId: varchar("social_id", { length: 255 }),
    socialName: varchar("social_name", { length: 255 }).notNull().default(""),
    message: text("message").notNull(),
    type: varchar("type", { length: 45 }).notNull().default(""),
    url: varchar("url", { length: 255 }),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    likes: integer("likes").notNull().default(0),
    shares: integer("shares").notNull().default(0),
    replies: integer("replies").notNull().default(0),
    status: socialPostStatusEnum("status").notNull().default("pending"),
    failureReason: text("failure_reason").notNull().default(""),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    attempts: integer("attempts").notNull().default(0),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    index("social_posts_profile_idx").on(t.profileId),
    index("social_posts_review_idx").on(t.reviewId),
    index("social_posts_status_idx").on(t.status),
  ],
);

/** v1 `social_post_media` — media attached to a social post. */
export const socialPostMedia = pgTable(
  "social_post_media",
  {
    postId: fk("post_id")
      .notNull()
      .references(() => socialPosts.id, { onDelete: "cascade" }),
    profileId: fk("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    mediaId: fk("media_id").notNull(),
    socialAccountId: fk("social_account_id"),
    socialId: varchar("social_id", { length: 255 }).notNull().default(""),
    status: socialPostStatusEnum("status").notNull().default("pending"),
    ...timestamps,
  },
  (t) => [primaryKey({ columns: [t.postId, t.mediaId] })],
);

/** v1 `social_campaigns` — automated review-to-social posting campaigns. */
export const socialCampaigns = pgTable("social_campaigns", {
  id: pk(),
  publicId: uuid("public_id").defaultRandom().notNull().unique(),
  profileId: fk("profile_id")
    .notNull()
    .references(() => profiles.id, { onDelete: "cascade" }),
  styleParams: jsonb("style_params"),
  cadence: varchar("cadence", { length: 255 }).notNull().default("1 Day"),
  postOn: varchar("post_on", { length: 255 }),
  preset: jsonb("preset"),
  type: varchar("type", { length: 255 }).notNull().default("review"),
  status: socialCampaignStatusEnum("status").notNull().default("inactive"),
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
  ...timestamps,
});

/** v1 `campaign_posts` — concrete scheduled posts generated by a social campaign. */
export const socialCampaignPosts = pgTable("social_campaign_posts", {
  id: pk(),
  campaignId: fk("campaign_id")
    .notNull()
    .references(() => socialCampaigns.id, { onDelete: "cascade" }),
  reviewId: fk("review_id").references(() => reviews.id, { onDelete: "set null" }),
  socialAccountId: fk("social_account_id"),
  description: text("description"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  status: campaignPostStatusEnum("status").notNull().default("scheduled"),
  processed: boolean("processed").notNull().default(false),
  ...timestamps,
});

/** v1 `scheduled_posts_automator` — automation rules producing scheduled posts. */
export const scheduledPostsAutomator = pgTable("scheduled_posts_automator", {
  id: pk(),
  campaignRef: varchar("campaign_ref", { length: 255 }).notNull(),
  profileId: fk("profile_id")
    .notNull()
    .references(() => profiles.id, { onDelete: "cascade" }),
  reviewId: fk("review_id").references(() => reviews.id, { onDelete: "set null" }),
  socialAccountId: fk("social_account_id").references(() => socialAccounts.id, {
    onDelete: "cascade",
  }),
  description: text("description"),
  styleParams: jsonb("style_params"),
  status: automatorStatusEnum("status").notNull().default("inactive"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  ...timestamps,
});

/** v1 `social_insight` — per-account metric timeseries. */
export const socialInsights = pgTable(
  "social_insights",
  {
    id: pk(),
    profileId: fk("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    socialAccountId: fk("social_account_id")
      .notNull()
      .references(() => socialAccounts.id, { onDelete: "cascade" }),
    name: varchar("name", { length: 255 }).notNull(),
    metric: varchar("metric", { length: 255 }).notNull(),
    value: varchar("value", { length: 255 }).notNull().default("0"),
    metricDate: timestamp("metric_date", { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("social_insights_unique_idx").on(
      t.profileId,
      t.socialAccountId,
      t.metric,
      t.metricDate,
    ),
    index("social_insights_profile_idx").on(t.profileId),
  ],
);

/** v1 `keyword_insight` — keyword analytics per account. */
export const keywordInsights = pgTable("keyword_insights", {
  id: pk(),
  profileId: fk("profile_id")
    .notNull()
    .references(() => profiles.id, { onDelete: "cascade" }),
  socialAccountId: fk("social_account_id"),
  keyword: text("keyword").notNull(),
  value: varchar("value", { length: 255 }).notNull(),
  ...timestamps,
});

/** v1 `platform_whitelist` — which social platforms a profile may use. */
export const platformWhitelist = pgTable("platform_whitelist", {
  id: pk(),
  profileId: fk("profile_id")
    .notNull()
    .references(() => profiles.id, { onDelete: "cascade" }),
  socialName: varchar("social_name", { length: 45 }).notNull(),
  ...timestamps,
});
